config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Flipper::UI.app(Flipper) => "/flipper"

  get "test_root", to: "rails/welcome#index", as: "test_root_rails"

  resources :locations, only: %i[index show new edit create update] do
    collection do
      get :print
      get :list
      get :pay
      get :signup
    end
    member do
      get :qr
    end
  end

  resource :feature, only: %i[show] do
    member do
      get :toggle
    end
  end

  get "/qr/:id" => "locations#qr"
  get "/:id" => "locations#show"
  root to: "locations#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feature.rb
class Feature
  FEATURES = [
    "new-page",
  ].freeze

  def self.validate_feature!(feature_name)
    raise ArgumentError, "feature is NOT valid #{feature_name.inspect}" unless FEATURES.include?(feature_name)
  end

  def self.enabled?(session, name)
    session && session[:features] && session[:features][name]
  end
end

app/models/location.rb
class Location < ApplicationRecord
  LOCATION_CODE_LENGTH = 4
  has_many :visits, dependent: :destroy
  enum status: {pending: 0, active: 1, archived: 2}

  scope :active_sample, -> { where(status: "active").where.not(code: nil).sample }
  validates :code, presence: true
  validates :code, length: {is: LOCATION_CODE_LENGTH}
  validates :code, uniqueness: true

  def hash_tag_text
    [
      [name, address].compact.reject(&:empty?).join(", "),
      "#qrtc",
      "#QRTC_art",
      "#qrtc_#{code}",
      "##{code}",
      "#streetart",
      "#streetartmelbourne",
      "#streetartaustralia",
    ].join(" ")
  end

  def url
    Location.url_for(id)
  end

  def qr_svg
    Location.qr_svg_for(id)
  end

  def self.url_for(location_id)
    uri = URI.parse(Rails.application.config.qrtc_base_url)
    uri.path = "/qr/#{location_id}"
    uri.to_s
  end

  def self.qr_svg_for(location_id)
    qrcode = RQRCode::QRCode.new(url_for(location_id))
    qrcode.as_svg(
      color: "212121",
      shape_rendering: "crispEdges",
      module_size: 11,
      standalone: true,
      use_path: true,
      viewbox: "0 0 500 500",
    ).html_safe # rubocop:disable Rails/OutputSafety
  end

  def set_code
    self.code ||= generate_code
  end

  private

  def generate_code
    loop do
      new_code = SecureRandom.alphanumeric(LOCATION_CODE_LENGTH)
      break new_code unless Location.exists?(code: new_code)
    end
  end
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :location
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  def show
  end

  def toggle
    Feature.validate_feature!(params[:name])

    feature_name = params[:name]

    session[:features] ||= {}
    session[:features][feature_name] = !session[:features][feature_name]
    redirect_to action: :show
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @location = Location.active_sample
    @location = nil unless @location.instance_of?(Location)
    @qr_svg = @location.qr_svg if @location
  end

  def list
    @locations = Location.all
  end

  def new
    @location = Location.new
  end

  def print
    @locations = Location.where(id: params[:ids])
  end

  def show
    @location = if params[:id].length == Location::LOCATION_CODE_LENGTH
      Location.find_by(code: params[:id])
    else
      Location.find(params[:id])
    end
    @qr_svg = @location.qr_svg
    if @location.status == "pending"
      @location.set_code
      render "edit"
    end
    @count = @location.visits.count

    render Feature.enabled?(session, "new-page") ? :new_show : :show
  end

  def edit
    @location = if params[:id].length == Location::LOCATION_CODE_LENGTH
      Location.find_by(code: params[:id])
    else
      Location.find(params[:id])
    end
    @location.set_code
    @qr_svg = @location.qr_svg
    @count = @location.visits.count
    @visits = @location.visits
  end

  def qr
    @location = Location.find(params[:id])
    @location.visits.create(meta_data: {
      user_agent: request.user_agent,
      remote_ip: request.remote_ip,
    })
    redirect_to "/#{@location.code}"
  end

  def create
    @locations = []
    params[:number].to_i.times do
      location = Location.new
      location.set_code
      location.save!
      @locations << location
    end
    redirect_to print_locations_path(ids: @locations.pluck(:id))
  end

  def update
    @location = Location.find(params[:id])
    @location.update!(location_params.merge(status: "active"))
    redirect_to "/#{@location.code}"
  end

  private

  def location_params
    params.require(:location).permit(:name, :address, :latitude, :longitude, :code)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/features/show.html.erb
<h1>features</h1>

<div class="container mt-3">
  <% Feature::FEATURES.each do |feature| %>
    <div class="row">
      <div class="column">
        <%= link_to(
          "toggle #{feature.inspect}",
          toggle_feature_path(name: feature),
          class: "button"
          ) %>
      </div>
      <div class="column">
        <%= session[:features] && session[:features][feature]&.inspect %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qrtc</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/edit.html.erb
<div class="container">
  <div class="row">
    <div class="column column-80 column-offset-10">
      <%= form_with model: @location do |f| %>
        <%= f.text_field :code, type: :hidden %>
        <div>
          <%= f.label :code %>
          <%= f.text_field :code, disabled: true %>
        </div>
        <div>
          <%= f.label :name %>
          <%= f.text_field :name %>
        </div>
        <div>
          <%= f.label :address %>
          <%= f.text_field :address %>
        </div>
        <div>
          <%= f.label :latitude %>
          <%= f.text_field :latitude %>
        </div>
        <div>
          <%= f.label :longitude %>
          <%= f.text_field :longitude %>
        </div>
        <%= f.submit %>
        <%= link_to "re print", print_locations_path(ids: @location.id), class: "button button-outline" %>
        <button type="button" onclick="useCurrentGeoLocation();">Use Current Geo Location</button>
      <% end %>
    </div>
  </div>
  <% if @visits %>
  <div class="row">
    <div class="column column-80 column-offset-10">
      <strong>Count:</strong> <%= @count %>
    </div>
  </div>
  <div class="row">
    <div class="column column-80 column-offset-10">
      <pre>
        <code>
          <%= JSON
                .pretty_generate(
                  @visits.map{ |visit| visit.attributes.slice("created_at", "meta_data") }
                ) %>
        </code>
      </pre>
    </div>
  </div>
  <% end %>
  <div class="row">
    <div class="column column-50 column-offset-25">
      <div class="qr-code">
        <%= @qr_svg %>
      </div>
    </div>
  </div>
</div>
<script>
  function useCurrentGeoLocation() {
    if(navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(function(position) {
        document.getElementById("location_latitude").value = position.coords.latitude;
        document.getElementById("location_longitude").value = position.coords.longitude;
      });
    } else {
        alert("Sorry, your browser does not support HTML5 geolocation.");
    }
  }
</script>

app/views/locations/generated.html.erb
<div class="container">
  <% @locations.each do |location| %>
      <div class="column">
        <div class="qr-container">
          <a href="<%= location.url %>" class="qr">
            <h1>QRTC.ART</h1>
            <div class="qr-code">
              <%= location.qr_svg %>
            </div>
          </a>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/locations/index.html.erb
<div class="container">
  <div class="row show-qrtc">
    <% if @location %>
      <div class="column column-50 hash-tags">
        <%= link_to "#QRTC_art", root_path, "data-turbolinks" => false %>
        <br />
        <%= @location.name.inspect %>
        <%= link_to(
          "##{@location.code}",
          "/#{@location.code}",
          class: "hash-tags-main",
          data: {
            testid: "qrtc-code-link",
            turbolinks: false
          }
        ) %>
        <div class="count">Count: <%= @count %></div>
      </div>
      <div class="column column-50 hash-tags">
        <div class="qr">
            <%= @qr_svg %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="column">
      <div id="pixlee_container"></div>
      <script type="text/javascript">
        window.PixleeAsyncInit = function() {
          Pixlee.init({apiKey:'181UZTCE_Zxhu0-cT95P'});
          Pixlee.addSimpleWidget({widgetId:'33314'});
        };
      </script>
      <script src="//instafeed.assets.pxlecdn.com/assets/pixlee_widget_1_0_0.js"></script>
    </div>
  </div>
</div>

app/views/locations/list.html.erb
<div class="container">
  <% @locations.each do |location| %>
    <%= link_to edit_location_path(location) do %>
      <div class="row">
      <div class="column">
        <%= location.name.inspect %>
      </div>
      <div class="column">
        <%= location.address.inspect %>
      </div>
      <div class="column">
        <%= location.status %>
      </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/locations/new.html.erb
<div class="container">
  <div class="qr-container">
    <div>
    <div>
      <%= form_with model: @location do |f| %>
        <label for="number">Number</label>
        <input id="number" name="number" type="text" />
        <%= f.submit "generate", type: "submit", class: "button-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/locations/new_show.html.erb
<div class="container">
  <div class="row">
    <div class="column"></div>
    <div class="column">
      <h1>QRTC.art</h1>
      <p class="tagline">Local Street Art Connect, Dicover and Appreciate</p>
    </div>
    <div class="column"></div>
  </div>
  <div class="row">
    <div class="column"></div>
    <div class="column">
      <button
        class="button block"
        data-toggle="modal"
        data-target="modal-find-next"
      >Discover</button>
      <button
        class="button block"
        data-toggle="modal"
        data-target="modal-pay-artist"
      >Appreciate</button>
      <button
        class="button block"
        data-toggle="modal"
        data-target="modal-connect"
      >Connect</button>
    </div>
    <div class="column"></div>
  </div>
</div>

<div class="container">
  <div class="mg-modal" id="modal-find-next">
    <div class="mg-modal--content container">
      <span class="mg-modal--closebtn mg-icon-close"></span>
      <h3>Discover</h3>
                      <div class="row">
      <div class="column"></div>
      <div class="column">
        <h1>QRTC.art</h1>
        <p class="tagline">Local Street Art Connect, Dicover and Appreciate</p>
      </div>
      <div class="column"></div>
    </div>
    <!-- comment -->
    </div>
  </div>
  <div class="mg-modal" id="modal-pay-artist">
    <div class="mg-modal--content container">
      <span class="mg-modal--closebtn mg-icon-close"></span>
      <h3>Appreciate</h3>
    <!-- comment -->
    </div>
  </div>
  <div class="mg-modal" id="modal-connect">
    <div class="mg-modal--content container">
      <span class="mg-modal--closebtn mg-icon-close"></span>
      <h3>Sign Up! to QRTC</h3>
      </div>
    </div>
  </div>
</div>

<script>
  function toggleModal(event) {
    var modal = document.querySelector(`#${event.target.dataset.target}`) ||
      document.querySelector(".mg-show");
    // if(event.target.classList && event.target.classList.contains("mg-show")) {
    //   console.log("yes")
    // }
    // TODO: work out how to close the modal if only the outer div is clicked and NOT the contents of the div
    modal.classList.toggle("mg-show")
    document
      .querySelectorAll(".mg-show")
      .forEach(element => element.addEventListener("click", toggleModal));
  }

  document
    .querySelectorAll("[data-toggle=modal]")
    .forEach(element => element.addEventListener("click", toggleModal));

  document
    .querySelectorAll(".mg-modal--closebtn")
    .forEach(element => element.addEventListener("click", toggleModal));

</script>

<script>
  function copy() {
    var copyText = document.querySelector("#input");
    copyText.select();
    document.execCommand("copy");
  }

  document.querySelector("#copy").addEventListener("click", copy);
</script>

app/views/locations/print.html.erb
<div class="container">
  <% @locations.each_with_index do |location, index| %>
    <% if index % 2 == 0 %>
      <div class="row" style="margin-bottom: 4em;">
    <% end %>
      <div class="column">
        <div class="qr-container">
          <a href="<%= location.url %>" class="qr">
            <h1>QRTC.ART</h1>
            <div class="qr-code">
              <%= location.qr_svg %>
            </div>
          </a>
        </div>
      </div>
    <% if index % 2 != 0 %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/locations/register.html.erb
<div class="container">
  <div class="row">
    <div class="column column-80 column-offset-10">
      <%= form_with model: @location do |f| %>
        <div>
          <%= f.label :name %>
          <%= f.text_field :name %>
        </div>
        <div>
          <%= f.label :address %>
          <%= f.text_field :address %>
        </div>
        <div>
          <%= f.label :latitude %>
          <%= f.text_field :latitude %>
        </div>
        <div>
          <%= f.label :longitude %>
          <%= f.text_field :longitude %>
        </div>
        <%= f.submit %>
        <%= link_to "re print", print_locations_path(ids: @location.id), class: "button button-outline" %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="column column-50 column-offset-25">
      <div class="qr-code">
        <%= @qr_svg %>
      </div>
    </div>
  </div>
</div>

app/views/locations/show.html.erb
<div class="container">
  <div class="row show-qrtc">
    <div class="column column-50 hash-tags">
      <%= link_to "#QRTC_art", root_path, "data-turbolinks" => false %>
      <br />
      <%= @location.name.inspect %>
      <div class="hash-tags-main">#<%= @location.code %></div>
      <input id="input" class="invisible-absolute-left" type="text" value="<%= @location.hash_tag_text %>"/>
      <button class="button button-outline" id="copy">Copy #hash tag</button>
      <div class="count">Count: <%= @count %></div>
    </div>
    <div class="column column-50 hash-tags">
      <div class="qr">
          <%= @qr_svg %>
      </div>
    </div>
  </div>
  <div id="pixlee_container"></div>
  <script type="text/javascript">
    window.PixleeAsyncInit = function() {
      Pixlee.init({apiKey:'181UZTCE_Zxhu0-cT95P'});
      Pixlee.addSimpleWidget({widgetId:'33314'});
    };
  </script>
  <script src="//instafeed.assets.pxlecdn.com/assets/pixlee_widget_1_0_0.js"></script>
</div>

<script>
  function copy() {
    var copyText = document.querySelector("#input");
    copyText.select();
    document.execCommand("copy");
  }

  document.querySelector("#copy").addEventListener("click", copy);
</script>